# Generated by Django 2.1.1 on 2018-10-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Tag',
            new_name='tags',
        ),
    ]
